/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.politecnicomalaga.ejercicio_var_3;

public class App {
    
    public static void main(String[] args){
    String nombre = "Ángel García Aguilera";
    System.out.println(nombre);
    }
}
